### ISSUE TITLE
Merger failed error due to minSdk version 9 in gradle

### ISSUE THREAD

**Issue by elirangoshen** [bugfender/rn-bugfender#12]
i just had this gradle sync error in my new project with rn 0.61.2
and needed to change this form 9 to 16. 
so i opened this issue for you to maybe consider change it at next version

**Comment by jgimenez** [comment]
Thanks Eliran, we'll check that

**Comment by janowskipio** [comment]
+1
_minSdkVersion - it describes the minimum Android OS version that your app will support. React Native supports all Android versions higher than 4.1 (API 16)._

I have a similar problem as well. The app fails to build because of rn-bugfender having lower (9) minSdkVersion than react-native (16).

So it's something important to consider changing in the next release 🙇

**Comment by franmontiel** [comment]
I'm glad to inform you that we've just released version 1.1.2 which solves this issue.

**Comment by janowskipio** [comment]
@franmontiel 
unfortunately, 1.1.2 doesn't fix the above problem.

full error:
`> Task :@bugfender_rn-bugfender:processDebugAndroidTestManifest FAILED
/Users/pithor/projects/PickNPack/node_modules/@bugfender/rn-bugfender/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger3714645792538277542.xml:5:5-73 Error:
        uses-sdk:minSdkVersion 9 cannot be smaller than version 16 declared in library [com.facebook.react:react-native:0.59.9] /Users/pithor/.gradle/caches/transforms-2/files-2.1/5bd6db72922f6720fa9afdc7358c87cb/AndroidManifest.xml as the library might be using APIs not available in 9
        Suggestion: use a compatible library with a minSdk of at most 9,
                or increase this project's minSdk version to at least 16,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)`

So it points to line https://github.com/bugfender/rn-bugfender/blob/master/android/build.gradle#L19

**Comment by franmontiel** [comment]
@janowskipio now it should be working fine with the new version 1.1.3. 
The previous version only updated Bugfender native dependency that now requires API 16 but didn't update the bridge project minSdkVersion value.

**Comment by janowskipio** [comment]
Issue fixed with 1.1.3 version, thanks!
